language: python
python:
  - 3.6
sudo: false
cache: "pip"
addons:
  apt:
    packages:
      - pandoc
install:
  - "pip install -r requirements.txt"
script:
  - "flake8 mongoengine_goodjson tests"
  - "radon cc -nc mongoengine_goodjson"
  - "tox"
after_success:
  - "coverage combine python27.coverage python36.coverage"
  - "coveralls"
before_deploy:
  - "pandoc -f markdown -t rst -o README.rst README.md"
  - "perl -pe \"s/\\[VERSION\\]/${TRAVIS_TAG}/\" setup.py > setup.py.new"
  - "mv setup.py.new setup.py"
  - "git config user.email 'travis@travis-ci.org'"
  - "git config user.name 'Travis Automated Commit'"
  - "git add ."
  - "git commit -m \"For release\""
  - >
      git archive --format tar.gz
      --prefix=mongoengine_goodjson-${TRAVIS_TAG}/
      -o ${HOME}/mongoengine_goodjson-${TRAVIS_TAG}.tgz HEAD
deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist
    on:
      tags: true
      python: 3.6
    user:
      secure: >-
        gI74GkBa26PaoXwMiYB0pSj9+B6LydY0bixIRQn6qqjSVrDYv9stDqILhlJ2lhHqOLOkg9
        3o8b5EqY4qZXAL2fllLw9SJFR/5LqFZQmR6SQIHoJPmLIJ57MLrYHn6OGI28aBnTms7zGk
        EnQcxaoT3X17Q/kpHI0U/s5vt6dhoWqYPPBZH6QdNBNx5of9FTjTT3O0vFN0E6Ejqaeiir
        DyL1el7aLQxgqWdKdq73ECjsn6/MZgTDwcGYDk0qGfNmDOLdPk9ZE9qwRXgw5c7vPY7QWU
        8Zl7pGPtzI8YO+TtLJuDd1NuYdKfhjdmQcTwdDxeFoBfhTtDIKT4i2vNBiY1mBVQFvqwhL
        mBnVJfO1TUgCPJOOwS9RqOtXeKSC4YDcZzR1upekDkWviKFMcrDqR7yNA3GKv7jFfECdDl
        usgfnLk5wjsXhmLtgeq2lU0r2BRU/vcibuehCKjST3GiddiCjdU+dZYZZpvEewwlTxwGMI
        B58kP79ZwcnF6LG7dAhWfKA1+EvIlgRCzJMBOYE0F4I3uS02PxpVnkj9EiUMPjOccCP0KO
        BmiF7bj7gGnR7MN1VXSDrw+UmyZWt1DvVsNmsb97lF/bF6QqQ6xqsPhY+KSjCTy4y2vaYp
        eVkyfM9FjXudYtkIsDEFcJhVKvoWjVnf+IhhGGJsMA3jjllooiILI=
    password:
      secure: >-
        e8nWJP5YdkYY/qSHCDQbKMhlWvA/oLZ/dF9Yf5+zNYura05ZteX6+fq92fNS0ATRytzWqm
        Kuk2vWXKG6eg/crbXgikxqTDuD/Q14bbMbOaR1nDudE+eYa7oTDgx+K7HiuNdmBjSYjroS
        1MO4FB+yTJrmPBlv3So5F3qELtk2qnTMoBGgbKb2Px09kIdPuaK5BxO4Ho8Bs0YFCBu6zk
        a4sfh25hJa6XOpiV0Ti8Vp3/N2X6aNrjKeBsNkQpDJcU17Q8eg1PMQPjr1ZWvgKqqdJc4m
        Wlmc/Ob9ElcqZ4wWVjWl7rtzgIYZd1MfnexOJcgtrM5+JJwROZyetN9/IJrqXVPGlCrlKp
        RYPrDZDxMCYQVljDTzHME5Xaa2J2gCvTI/GYVYwWoXuIXU5lEUMqlGxGS/t5tewsscT1DC
        pd/24VVwiFJj49yuUeroryG3lpl1L8/wrC/0hyjaupNETsNYKXjnbCPmq5JyKJABHpPAKO
        yUci97FBu5zDR48By44CmDvJOffGnxPFRQ5LdfJk1dnRr7SqPV4LnPwJu7m90tJn4TWpLT
        PY8qCIjDHdD/gz7sSOoi4Zg1+59fgbycjnJItMxymsKesh7l7J3rMkMoeBIPgRCHOPJAix
        jWQa4OpcDhXUyh26liws6MI5e7ESigthN4ksS+LAFWP2jxOdxU+oE=
  - provider: releases
    file: "${HOME}/mongoengine_goodjson-${TRAVIS_TAG}.tgz"
    skip_cleanup: true
    on:
      tags: true
      python: 3.6
    api_key:
      secure: >-
        K38bWhQWubBzIYuGuV96VBJRV1BPQmKAIzmjOJgPv76kRH2bvCGf4ekFKqnT2CVPWnSNGd
        1JH0EoRAznV2tMbY/MfVnT00TQtf8fcR93xODmoaNX0+V5hhRJaEaj4ygrzvKQjuHjGXkA
        zrX272R9DUJ2IGNzTIXyKrlV6Cr2lsnOfOXGVLOq0EeEdtj/rbgUzcBa+EVhEFDfTsqIh2
        y6b1cS7u0ksJc0Ypk90dYVUt7FYMuKBSXsl0dEdUNS1+1akGG0XLymCiyE2FXCSTsvvalq
        H6nziRfsxdSa8ETqlwspoDnDWRQWuJOaa1dXOJEzKZ5TJyiWcuIyJCgYi9ZDUIhTKSBlTt
        GATvRalzen/xqiw/iSy3GS344EJoK6gir9T/D55xt3DSsl/Ioo611s0d0xWmF08w5RlZRP
        kQkofNPB3/I7vuK54mx7wmmUg3waZJw1KQLNvRrxfYWtndgnF0p6XC6xhX9lzYMpLRL6wW
        wjY8A1Ej+AbOy9Uw31VmHRM+v0z1vMlDdfYMfCr8C5kcQSzEfJpOnzXSr78VMHxlWtQ3e3
        yAuN01CBk7jSX9NQpkqOgzPB5QLaYu1IHSOCVn0N/2pwJvTP30e0SaCL3GQwMtjcN8F7/a
        hnc3AngvPjGkRYrQTvd3eZKXydAfMPaF2R51RM5w/qWHWn2Ny9tEc=
